name: Parallelism
author: Austen Stone
description: Split a job into multiple parallel jobs
branding:
  icon: "plus"
  color: "blue"

inputs:
  count:
    description: "Number of times to run"
    required: true
    default: 10

outputs:
  matrix:
    description: "The matrix input"
  count:
    description: "Number of times run"

runs:
  using: "node20"
  main: "dist/index.js"
