name: Usage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  parallelism:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parallel.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: parallel
        uses: ./
  run:
    needs: parallelism
    runs-on: ubuntu-latest
    strategy:
      matrix:
        parallel: ${{ fromJson(needs.parallelism.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.parallel.count }} / ${{ matrix.parallel.total }}